name: Query subprojects documentation issues

on:
  schedule:
    - cron: '5 5 * * *'  # Runs daily at 5:05am UTC

  workflow_dispatch:


jobs:
  query-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install requests

    - name: Fetch Documentation Issues
      run: |
        cd workflows/documentation_issues
        python fetch_issues.py --write-md ../documentation_issues.md

    - name: Commit and Push if Changes Exist
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git diff --staged --quiet || git commit -m "Update documentation issues"
        git push
